MEMORY {
	VNAND_2048: ORIGIN = 0x1e00000 LENGTH=2048
	VFLASH: ORIGIN = 0x1e00800 LENGTH = 132K-2048
	SDRAM:  ORIGIN = 0x1e20000 LENGTH = 1M-132K
}
SECTIONS {
	GROUP:{
		.start ALIGN(4) TYPE(TEXT):{
			crt1.o(.text)
			
		}
		* (TEXT): {}
		* (LIT):{}
		.aminit ALIGN(4) SIZE(0) TYPE(LIT):{
		}
	}>VFLASH
	GROUP: {
		* (DATA): {}
		* (BSS): {}
		.stack ALIGN(4)  SIZE(DEFINED _STACKSIZE?_STACKSIZE:65536): {}
	} > SDRAM
}
_MEM_SDRAM_START=ADDR(SDRAM);
_MEM_SDRAM_END=ADDR(SDRAM)+SIZEOF(SDRAM);
_MEM_FREE_START=ADDR(.stack)+SIZEOF(.stack);
_MEM_FREE_SIZE=ADDR(SDRAM)+SIZEOF(SDRAM)-ADDR(.stack)-SIZEOF(.stack);
_MEM_START=0x1c00000;
_MEM_END=ADDR(VFLASH);
